### ISSUE TITLE
Calibration Out

### ISSUE THREAD

**Issue by naigy81** [saper-2/rpi-5inch-hdmi-touchscreen-driver#1]
Hi,

Firstly thanks for making this available for the 5" screen. I have followed through your guide and now have if working for the most part. When I try and calibrate it myself with the 5 point calibration it appears to be way out. When I have imported your figures the screen works almost perfect however I can't access about 5 - 10 mm all the way around the screen. 

I have tried recalibrating several times but it never seems to go even close to the demo numbers I have tried from your guide.

Can you give firm details on what each of the parameters are so I can fine tune it to hopefully improve the responsiveness of the screen on the outer edges.

Per your guide you had the following numbers
`13679 16 -1843476 -48 8414 -1707140 65536 800 480` 
where as mine I have got
`79744 -24373 -3790564 -7248 83188 1305748 65536 800 480`
I understand the last 3 but could you elaborate on the first 6 and that may help me with tweaking the calibration manually

Thanks in advance.

**Comment by saper-2** [comment]
Those 6 variables are used in one of tslib filters for calibrating touch. Sorry, don't remember it anymore, check code for tslib - look into code of raw_input or linear - there are 2 or 3 equations that using those 6 calib. constants.
