### ISSUE TITLE
the instructions do not work for me

### ISSUE THREAD

**Issue by bcopy** [saper-2/rpi-5inch-hdmi-touchscreen-driver#2]
- My display is working
- dmesg reveals : 

```
hid-generic 0003:0EEF:0005.0001: hiddev0,hidraw0: USB HID v1.10 Device [RPI_TOUCH By ZH851] on usb-20980000.usb-1.2/input0
```
-  testing /dev/hidraw0 works fine :

```
    sudo xxd -c 22 /dev/hidraw0
```

shows the expected result upon touch.
- I build and install tslib as per the instructions, all fine
- running ts_test does not work :

```
    sudo TSLIB_CONFFILE=/etc/ts.conf TSLIB_FBDEVICE=/dev/fb0 ts_test
```

and yet nothing happens when I touch the screen.
- The input device /dev/input/event0 is also non-reactive.

**Comment by bcopy** [comment]
ts_test doesn't work, but touch.py does, so closing this.

**Comment by saper-2** [comment]
Sorry for delay, but I used non-raspi tslib (I had to compile one myself...).
But if work for you then it's fine :)
