### ISSUE TITLE
Touch Screen Test Error

### ISSUE THREAD

**Issue by santhoshrsk** [saper-2/rpi-5inch-hdmi-touchscreen-driver#3]
Hi, I am using Ubuntu 16.04 in my Development board Nvidia TX1, I am trying to integrate a touch screen to board. I have followed your steps upto install tslib, after that when i give test command it gives me error as given below,

" ubuntu@tegra-ubuntu:~/tslib/tslib$ sudo TSLIB_CONFFILE=/etc/ts.conf TSLIB_FBDEVICE=/dev/fb0 ts_test
**\* Error in `ts_test': double free or corruption (!prev): 0x0000000000415040 ***
Segmentation fault"

I am using Waveshare 5inch LCD TS only, did i miss anything. 
Thanks in advance.

**Comment by saper-2** [comment]
Hi,
Sorry I can't help you, and for late answer. There **might be** something wrong with compiler for you processor or your environment (e.g. compiler config file, libs versions, etc.). When I googled "nvidia tx1 double free or corruption" then there came few results - check this, there might be something that help you.
